name: 'Create JIRA Release'
description: 'Creates a JIRA release containing tickets referenced in commit subjects'
author: 'Alexander Hirdman'
inputs:
  github-token:
    required: true
    description: 'github token'
runs:
  using: 'node16'
  main: 'dist/index.js'
